#!/usr/bin/env python3
"""Cargoless APFS offset audit.

This verifies the parser-development constants and synthetic fixture byte layouts
that are known before real macOS fixtures are available. It does not claim the
Rust parser is correct for production APFS; it catches drift between the local
source constants, fixture generator assumptions, and manifests.
"""
from __future__ import annotations
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / "APFS_OFFSET_AUDIT.json"
OUT_MD = ROOT / "APFS_OFFSET_AUDIT.md"

EXPECTED_CONSTANTS = {
    "APFS_OBJECT_HEADER_SIZE": 32,
    "NX_SUPERBLOCK_MIN_SIZE": 184,
    "GPT_SECTOR_SIZE": 512,
    "GPT_HEADER_MIN_SIZE": 92,
    "GPT_PARTITION_ENTRY_MIN_SIZE": 128,
    "CHECKPOINT_MAP_HEADER_SIZE": 40,
    "CHECKPOINT_MAPPING_SIZE": 40,
    "OMAP_PHYS_MIN_SIZE": 88,
    "APFS_VOLUME_SUPERBLOCK_MIN_SIZE": 770,
    "APFS_VOLUME_NAME_OFFSET": 512,
    "APFS_VOLUME_NAME_LEN": 256,
    "APFS_VOLUME_ROLE_OFFSET": 768,
    "BTREE_NODE_MIN_SIZE": 56,
    "BTREE_TOC_ENTRY_SIZE": 4,
    "OMAP_KEY_SIZE": 16,
    "OMAP_VALUE_SIZE": 16,
}

FIXTURE_CHECKS = [
    {"path": "fixtures/synthetic-nxsb-block0.bin", "offset": 32, "bytes": b"NXSB", "label": "block-zero NXSB magic"},
    {"path": "fixtures/synthetic-checkpoint-ring.img", "offset": 32, "bytes": b"NXSB", "label": "checkpoint-ring block-zero NXSB magic"},
    {"path": "fixtures/synthetic-gpt-apfs.img", "offset": 512, "bytes": b"EFI PART", "label": "GPT header signature"},
    {"path": "fixtures/synthetic-volume-superblock.img", "offset": 32, "bytes": b"NXSB", "label": "volume fixture container NXSB"},
]

APFS_GPT_TYPE_GUID_BYTES = bytes([
    0xef, 0x57, 0x34, 0x7c, 0x00, 0x00, 0xaa, 0x11,
    0xaa, 0x11, 0x00, 0x30, 0x65, 0x43, 0xec, 0xac,
])

def fail(message: str) -> None:
    raise SystemExit(f"apfs-offset-audit: ERROR: {message}")

def parse_constants() -> dict[str, int]:
    text = (ROOT / "crates/apfs-types/src/lib.rs").read_text(encoding="utf-8")
    constants: dict[str, int] = {}
    for match in re.finditer(r"pub const\s+([A-Z0-9_]+):\s+[^=]+\s*=\s*([^;]+);", text):
        name, value_text = match.group(1), match.group(2).strip()
        if name not in EXPECTED_CONSTANTS:
            continue
        value_text = value_text.replace("_", "")
        try:
            constants[name] = int(value_text, 0)
        except ValueError:
            pass
    return constants

def check_fixture_bytes(item: dict) -> dict:
    path = ROOT / item["path"]
    if not path.exists():
        return {"path": item["path"], "label": item["label"], "status": "missing"}
    data = path.read_bytes()
    offset = item["offset"]
    expected = item["bytes"]
    observed = data[offset:offset + len(expected)]
    return {
        "path": item["path"],
        "label": item["label"],
        "offset": offset,
        "expected_hex": expected.hex(),
        "observed_hex": observed.hex(),
        "status": "pass" if observed == expected else "fail",
    }

def check_gpt_apfs_guid() -> dict:
    path = ROOT / "fixtures/synthetic-gpt-apfs.img"
    if not path.exists():
        return {"path": str(path.relative_to(ROOT)), "status": "missing"}
    data = path.read_bytes()
    # The synthetic generator stores partition entries starting at LBA 2.
    offset = 512 * 2
    observed = data[offset:offset + 16]
    return {
        "path": "fixtures/synthetic-gpt-apfs.img",
        "label": "APFS GPT type GUID bytes at first partition entry",
        "offset": offset,
        "expected_hex": APFS_GPT_TYPE_GUID_BYTES.hex(),
        "observed_hex": observed.hex(),
        "status": "pass" if observed == APFS_GPT_TYPE_GUID_BYTES else "fail",
    }

def main() -> int:
    constants = parse_constants()
    constant_results = []
    for name, expected in EXPECTED_CONSTANTS.items():
        observed = constants.get(name)
        constant_results.append({
            "name": name,
            "expected": expected,
            "observed": observed,
            "status": "pass" if observed == expected else "fail",
        })
    fixture_results = [check_fixture_bytes(item) for item in FIXTURE_CHECKS]
    fixture_results.append(check_gpt_apfs_guid())
    all_results = constant_results + fixture_results
    failing = [item for item in all_results if item.get("status") != "pass"]
    report = {
        "schema_version": "0.25.0",
        "status": "pass" if not failing else "fail",
        "constant_results": constant_results,
        "fixture_results": fixture_results,
        "failure_count": len(failing),
        "note": "Cargoless parser-development audit; not a substitute for real APFS fixtures or cargo tests.",
    }
    OUT_JSON.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    lines = ["# APFS Offset Audit", "", "Generated by `tools/apfs_offset_audit.py`.", "", f"Status: **{report['status']}**", "", "## Constants", "", "| Constant | Expected | Observed | Status |", "|---|---:|---:|---|"]
    for item in constant_results:
        lines.append(f"| `{item['name']}` | {item['expected']} | {item['observed']} | `{item['status']}` |")
    lines += ["", "## Fixture byte checks", "", "| Fixture | Label | Offset | Status |", "|---|---|---:|---|"]
    for item in fixture_results:
        lines.append(f"| `{item.get('path')}` | {item.get('label','')} | {item.get('offset','')} | `{item.get('status')}` |")
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    if failing:
        fail(f"{len(failing)} audit checks failed")
    print("apfs-offset-audit: passed")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
