#!/usr/bin/env python3
"""Generate a cargoless Rust public API surface snapshot."""
from __future__ import annotations
import argparse, json, re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def current_version(root: Path) -> str:
    version_file = root / 'VERSION'
    return version_file.read_text(encoding='utf-8').strip() if version_file.exists() else '0.0.0-dev'
ITEM_RE = re.compile(r'^\s*pub\s+(?:async\s+)?(struct|enum|trait|fn|const|type)\s+([A-Za-z_][A-Za-z0-9_]*)', re.M)

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--root', type=Path, default=ROOT)
    args = parser.parse_args()
    root = args.root.resolve()
    items = []
    for path in sorted((root / 'crates').rglob('*.rs')):
        text = path.read_text(encoding='utf-8')
        crate = path.relative_to(root).parts[1]
        for match in ITEM_RE.finditer(text):
            items.append({
                'crate': crate,
                'path': path.relative_to(root).as_posix(),
                'kind': match.group(1),
                'name': match.group(2),
            })
    payload = {'schema_version': current_version(root), 'item_count': len(items), 'items': items}
    (root / 'API_SURFACE.json').write_text(json.dumps(payload, indent=2) + '\n', encoding='utf-8')
    lines = ['# APFS-RS Public API Surface Snapshot', '', 'Generated by `tools/api_surface_snapshot.py`.', '', f"Public items discovered: **{len(items)}**", '', '| Crate | Kind | Name | Path |', '|---|---|---|---|']
    for item in items:
        lines.append(f"| `{item['crate']}` | `{item['kind']}` | `{item['name']}` | `{item['path']}` |")
    (root / 'API_SURFACE.md').write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'api-surface-snapshot: wrote API_SURFACE.json and API_SURFACE.md ({len(items)} items)')
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
