#!/usr/bin/env python3
"""Export remaining production blockers as reviewable issue templates."""
from __future__ import annotations
import json
from pathlib import Path
try:
    import yaml
except Exception as exc:  # pragma: no cover
    raise SystemExit(f"PyYAML required: {exc}")

ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / "BACKLOG_ISSUE_EXPORT.json"
OUT_MD = ROOT / "BACKLOG_ISSUE_EXPORT.md"
ISSUE_DIR = ROOT / "docs/generated-issues"

def slug(text: str) -> str:
    return ''.join(ch.lower() if ch.isalnum() else '-' for ch in text).strip('-').replace('--','-')[:80]

def main() -> int:
    data = yaml.safe_load((ROOT / "REMAINING_ELEMENTS.yaml").read_text(encoding="utf-8"))
    remaining = data.get("remaining", [])
    ISSUE_DIR.mkdir(parents=True, exist_ok=True)
    items = []
    for item in remaining:
        item_id = item.get("id", "UNKNOWN")
        title = item.get("title", item_id)
        classification = item.get("classification", "remaining")
        category = item.get("category", "unknown")
        filename = f"{item_id.lower()}-{slug(title)}.md"
        body = f"""# {item_id}: {title}\n\n## Classification\n\n`{classification}`\n\n## Category\n\n`{category}`\n\n## Codev / Conductor context\n\n- Read `REQUIREMENTS.md`.\n- Read `REMAINING_ELEMENTS.md`.\n- Read `PRODUCTION_GAP_REPORT.md`.\n- Create/update a Codev spec, plan, and review when implementation starts.\n- Create/update a Conductor track when implementation starts.\n\n## Safety\n\nPreserve read-only defaults. Do not add raw physical-device writes, encryption bypass, repair, format, or live mount lifecycle unless a dedicated accepted spec requires it.\n\n## Acceptance\n\nTo be completed by the local/platform implementation loop.\n"""
        (ISSUE_DIR / filename).write_text(body, encoding="utf-8")
        items.append({"id": item_id, "title": title, "classification": classification, "category": category, "path": f"docs/generated-issues/{filename}"})
    report = {"schema_version": "0.25.0", "issue_count": len(items), "issues": items}
    OUT_JSON.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    lines = ["# Backlog Issue Export", "", "Generated by `tools/backlog_issue_export.py`.", "", f"Generated issue stubs: **{len(items)}**", "", "| ID | Title | Issue stub |", "|---|---|---|"]
    for item in items:
        lines.append(f"| `{item['id']}` | {item['title']} | `{item['path']}` |")
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"backlog-issue-export: wrote {len(items)} issue stubs")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
