#!/usr/bin/env python3
"""Generate a cargoless Cargo workspace dependency graph from Cargo.toml files."""
from __future__ import annotations
import argparse, json, tomllib
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]


def parse_manifest(path: Path) -> dict:
    return tomllib.loads(path.read_text(encoding="utf-8"))


def package_name(manifest: dict, fallback: str) -> str:
    return manifest.get("package", {}).get("name", fallback)


def path_deps(manifest: dict) -> list[str]:
    deps = []
    for section in ("dependencies", "dev-dependencies", "build-dependencies"):
        for name, value in manifest.get(section, {}).items():
            if isinstance(value, dict) and "path" in value:
                deps.append(name)
    return sorted(set(deps))


def build_graph() -> dict:
    root_manifest = parse_manifest(ROOT / "Cargo.toml")
    members = root_manifest.get("workspace", {}).get("members", [])
    crates = []
    edges = []
    for member in members:
        manifest_path = ROOT / member / "Cargo.toml"
        if not manifest_path.exists():
            continue
        manifest = parse_manifest(manifest_path)
        name = package_name(manifest, Path(member).name)
        crates.append({"name": name, "member": member, "version": manifest.get("package", {}).get("version")})
        for dep in path_deps(manifest):
            edges.append({"from": name, "to": dep})
    return {"schema_version": (ROOT / "VERSION").read_text(encoding="utf-8").strip(), "crates": crates, "edges": edges}


def write_md(graph: dict, path: Path) -> None:
    lines = ["# Cargo Dependency Graph", "", "Generated by `tools/cargo_dependency_graph.py`.", "", "```mermaid", "graph LR"]
    if graph["edges"]:
        for edge in graph["edges"]:
            lines.append(f"  {edge['from'].replace('-', '_')}[{edge['from']}] --> {edge['to'].replace('-', '_')}[{edge['to']}]")
    else:
        for crate in graph["crates"]:
            lines.append(f"  {crate['name'].replace('-', '_')}[{crate['name']}]")
    lines += ["```", "", "## Crates", "", "| Crate | Member | Version |", "|---|---|---|"]
    for crate in graph["crates"]:
        lines.append(f"| `{crate['name']}` | `{crate['member']}` | `{crate.get('version')}` |")
    lines += ["", "## Path dependency edges", "", "| From | To |", "|---|---|"]
    for edge in graph["edges"]:
        lines.append(f"| `{edge['from']}` | `{edge['to']}` |")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--json-out", type=Path, default=ROOT / "CARGO_DEPENDENCY_GRAPH.json")
    p.add_argument("--md-out", type=Path, default=ROOT / "CARGO_DEPENDENCY_GRAPH.md")
    args = p.parse_args()
    graph = build_graph()
    args.json_out.write_text(json.dumps(graph, indent=2) + "\n", encoding="utf-8")
    write_md(graph, args.md_out)
    print(f"cargo-dependency-graph: wrote {args.json_out} and {args.md_out}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
