#!/usr/bin/env python3
"""Generate a cargoless CLI command contract snapshot from crates/apfs-cli."""
from __future__ import annotations
import argparse, json, re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

SPECIAL_NAMES = {
    'CompatibilityReport': 'compatibility-report',
    'LookupObject': 'lookup-object',
    'ResolverReport': 'resolver-report',
    'BtreeCursorReport': 'btree-cursor-report',
    'ReadObject': 'read-object',
    'DiagnosticsExport': 'diagnostics-export',
    'DiagnosticsBundle': 'diagnostics-bundle',
    'PathPolicy': 'path-policy',
    'FeatureReadiness': 'feature-readiness',
    'MetadataFeatureReport': 'metadata-feature-report',
    'MountPlan': 'mount-plan',
}

COMMAND_DESCRIPTIONS = {
    'inspect': 'Read-only APFS source inspection report.',
    'compatibility-report': 'Safety-oriented alias for inspect workflows.',
    'doctor': 'Aggregated read-only readiness and blocker report.',
    'diagnostics-export': 'Redacted host-side diagnostic bundle export.',
    'lookup-object': 'Synthetic/read-only object-map lookup facade.',
    'volumes': 'Synthetic/read-only APFS volume report.',
    'resolver-report': 'Object-map resolver availability report.',
    'btree-cursor-report': 'Production-shaped B-tree cursor report.',
    'read-object': 'Mapped object block read report.',
    'ls': 'Synthetic directory listing.',
    'cat': 'Synthetic file preview.',
    'stat': 'Synthetic directory-entry metadata report.',
    'extract': 'Synthetic safe host-side extract preview.',
    'mount-plan': 'Windows read-only mount preflight plan; does not mount.',
    'diagnostics-bundle': 'Redacted in-memory diagnostics bundle report.',
    'path-policy': 'Unicode/case-sensitivity and host-path safety policy report.',
    'feature-readiness': 'Advanced APFS feature readiness report.',
    'metadata-feature-report': 'Synthetic metadata feature model report.',
}

def current_version(root: Path) -> str:
    version_file = root / 'VERSION'
    return version_file.read_text(encoding='utf-8').strip() if version_file.exists() else '0.0.0-dev'


def kebab(name: str) -> str:
    if name in SPECIAL_NAMES:
        return SPECIAL_NAMES[name]
    return re.sub(r'(?<!^)([A-Z])', r'-\1', name).lower()

def extract_command_block(text: str) -> str:
    start = text.index('enum Command')
    brace = text.index('{', start)
    depth = 0
    for idx in range(brace, len(text)):
        if text[idx] == '{':
            depth += 1
        elif text[idx] == '}':
            depth -= 1
            if depth == 0:
                return text[brace + 1:idx]
    raise RuntimeError('could not find Command enum end')

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--root', type=Path, default=ROOT)
    parser.add_argument('--json-out', type=Path, default=None)
    parser.add_argument('--markdown-out', type=Path, default=None)
    args = parser.parse_args()
    root = args.root.resolve()
    cli = (root / 'crates/apfs-cli/src/main.rs').read_text(encoding='utf-8')
    block = extract_command_block(cli)
    variants = []
    for match in re.finditer(r'^\s*([A-Z][A-Za-z0-9_]*)\s*\{', block, flags=re.M):
        rust_name = match.group(1)
        command = kebab(rust_name)
        variants.append({
            'rust_variant': rust_name,
            'command': command,
            'description': COMMAND_DESCRIPTIONS.get(command, 'No description recorded.'),
            'read_only': command not in {'extract'} or True,
            'writes_to_apfs_media': False,
        })
    payload = {
        'schema_version': current_version(root),
        'command_count': len(variants),
        'commands': variants,
        'safety_note': 'All current commands are read-only with respect to APFS media. extract writes only to a host destination directory for synthetic fixture previews.',
    }
    json_out = args.json_out or (root / 'CLI_CONTRACT.json')
    md_out = args.markdown_out or (root / 'CLI_CONTRACT.md')
    json_out.write_text(json.dumps(payload, indent=2) + '\n', encoding='utf-8')
    lines = ['# APFS-RS CLI Contract', '', 'Generated by `tools/cli_contract_snapshot.py`.', '', f"Schema version: `{payload['schema_version']}`", '', '| Command | Rust variant | Description | Writes APFS media |', '|---|---|---|---|']
    for item in variants:
        lines.append(f"| `apfs {item['command']}` | `{item['rust_variant']}` | {item['description']} | `{str(item['writes_to_apfs_media']).lower()}` |")
    lines += ['', '## Safety note', '', payload['safety_note']]
    md_out.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'cli-contract-snapshot: wrote {json_out.relative_to(root)} and {md_out.relative_to(root)} ({len(variants)} commands)')
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
