#!/usr/bin/env python3
"""Run a fast current-environment self-test without invoking Cargo.

This uses in-process runpy where possible to avoid subprocess hangs in constrained
sandboxes. It is not a substitute for cargo test.
"""
from __future__ import annotations
import json, py_compile, runpy, sys, time, traceback
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / "CURRENT_ENV_SELFTEST.json"
OUT_MD = ROOT / "CURRENT_ENV_SELFTEST.md"
PY_COMPILE = [
    "tools/apfs_offset_audit.py",
    "tools/golden_output_generator.py",
    "tools/dependency_license_policy_check.py",
    "tools/backlog_issue_export.py",
    "tools/current_env_selftest.py",
    "tools/tool_capability_matrix.py",
    "tools/rust_static_lint.py",
    "tools/local_command_plan.py",
    "tools/mvp_blocker_tasklist.py",
    "tools/agent_handoff_brief.py",
]
SCRIPTS = [
    "tools/apfs_offset_audit.py",
    "tools/golden_output_generator.py",
    "tools/dependency_license_policy_check.py",
    "tools/backlog_issue_export.py",
    "tools/synthetic_fixture_oracle.py",
    "tools/tool_capability_matrix.py",
    "tools/rust_static_lint.py",
    "tools/local_command_plan.py",
    "tools/mvp_blocker_tasklist.py",
    "tools/agent_handoff_brief.py",
]

def run_py_compile() -> dict:
    start = time.time()
    try:
        for rel in PY_COMPILE:
            py_compile.compile(str(ROOT / rel), doraise=True)
        return {"command": "py_compile selected tools", "returncode": 0, "duration_seconds": round(time.time()-start,3), "status":"pass", "error_tail":""}
    except Exception:
        return {"command": "py_compile selected tools", "returncode": 1, "duration_seconds": round(time.time()-start,3), "status":"fail", "error_tail": traceback.format_exc()[-1000:]}

def run_script(rel: str) -> dict:
    start = time.time(); old_argv = sys.argv[:]
    try:
        sys.argv = [rel]
        runpy.run_path(str(ROOT / rel), run_name="__main__")
        rc = 0; err = ""
    except SystemExit as exc:
        rc = exc.code if isinstance(exc.code, int) else (0 if exc.code is None else 1)
        err = "" if rc == 0 else str(exc)
    except Exception:
        rc = 1; err = traceback.format_exc()[-1000:]
    finally:
        sys.argv = old_argv
    return {"command": f"runpy {rel}", "returncode": rc, "duration_seconds": round(time.time()-start,3), "status": "pass" if rc == 0 else "fail", "error_tail": err}

def main() -> int:
    results = [run_py_compile()]
    results.extend(run_script(rel) for rel in SCRIPTS)
    failed = [item for item in results if item["returncode"] != 0]
    report = {"schema_version": "0.27.0", "status": "pass" if not failed else "fail", "check_count": len(results), "failure_count": len(failed), "results": results}
    OUT_JSON.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    lines = ["# Current Environment Self-Test", "", "Generated by `tools/current_env_selftest.py`.", "", f"Status: **{report['status']}**", f"Checks: **{len(results)}**", f"Failures: **{len(failed)}**", "", "| Status | Command | Seconds |", "|---|---|---:|"]
    for item in results:
        lines.append(f"| `{item['status']}` | `{item['command']}` | {item['duration_seconds']} |")
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    if failed:
        print("current-env-selftest: failures detected", file=sys.stderr)
        return 1
    print("current-env-selftest: passed")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
