#!/usr/bin/env python3
"""Classify remaining items by what can and cannot be completed in this sandbox."""
from __future__ import annotations
import argparse, json
from pathlib import Path
try:
    import yaml  # type: ignore
except Exception:
    yaml = None
ROOT = Path(__file__).resolve().parents[1]

LOCAL_ONLY_KEYWORDS = ["Rust", "macOS", "real fixture", "WinFsp", "Windows", "CI", "production"]

CURRENT_ENV_OPTIONAL: list[dict] = []

OPEN_ENDED_POLISH_EXAMPLES = [
    "Add still more synthetic negative fixtures.",
    "Add more narrative examples to handoff docs.",
    "Add more static heuristics for possible Cargo failures.",
]


def load_yaml(path: Path):
    if yaml is None:
        raise SystemExit("PyYAML is required")
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def classify_item(item: dict, force_local: bool = False) -> dict:
    text = " ".join(str(item.get(k, "")) for k in ("id", "title", "dependency"))
    needs_local = force_local or any(k.lower() in text.lower() for k in LOCAL_ONLY_KEYWORDS)
    return {**item, "current_environment_completable": False if needs_local else True, "classification": "local_or_platform_required" if needs_local else "possibly_current_environment"}


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--json-out", type=Path, default=ROOT / "CURRENT_ENVIRONMENT_REMAINING.json")
    p.add_argument("--md-out", type=Path, default=ROOT / "CURRENT_ENVIRONMENT_REMAINING.md")
    args = p.parse_args()
    remaining = load_yaml(ROOT / "REMAINING_ELEMENTS.yaml")
    mvp = [classify_item(i, force_local=True) for i in remaining.get("remaining_windows_readonly_mvp", [])]
    post = [classify_item(i, force_local=True) for i in remaining.get("remaining_beyond_mvp", [])]
    completable_mvp = [i for i in mvp if i["current_environment_completable"]]
    completable_post = [i for i in post if i["current_environment_completable"]]
    payload = {
        "schema_version": (ROOT / "VERSION").read_text(encoding="utf-8").strip(),
        "summary": {
            "mvp_remaining": len(mvp),
            "post_mvp_remaining": len(post),
            "production_remaining_total": len(mvp) + len(post),
            "production_items_completable_in_current_environment": len(completable_mvp) + len(completable_post),
            "optional_current_environment_improvements_remaining": len(CURRENT_ENV_OPTIONAL),
        },
        "remaining_windows_readonly_mvp": mvp,
        "remaining_beyond_mvp": post,
        "optional_current_environment_improvements": CURRENT_ENV_OPTIONAL,
        "open_ended_polish_examples": OPEN_ENDED_POLISH_EXAMPLES,
        "conclusion": "No production APFS or Windows MVP blockers can be honestly completed in this environment without Rust/macOS/Windows execution. The remaining work is local/platform-dependent; further sandbox work would be optional polish rather than required implementation.",
    }
    args.json_out.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    lines = ["# Current-Environment Remaining Work", "", "Generated by `tools/current_env_remaining.py`.", "", f"- Production remaining total: **{payload['summary']['production_remaining_total']}**", f"- Production items completable in this environment: **{payload['summary']['production_items_completable_in_current_environment']}**", f"- Optional current-environment improvements remaining: **{payload['summary']['optional_current_environment_improvements_remaining']}**", "", "## MVP blockers", "", "| ID | Title | Classification |", "|---|---|---|"]
    for item in mvp:
        lines.append(f"| `{item['id']}` | {item['title']} | `{item['classification']}` |")
    lines += ["", "## Optional current-environment improvements", "", "No required current-environment items remain after this handoff-hardening pass. Open-ended polish examples remain possible but are no longer counted as implementation blockers:", ""]
    for item in OPEN_ENDED_POLISH_EXAMPLES:
        lines.append(f"- {item}")
    lines += ["", "## Conclusion", "", payload["conclusion"]]
    args.md_out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"current-env-remaining: wrote {args.json_out} and {args.md_out}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
