#!/usr/bin/env python3
"""Inventory tools available in the current non-Rust sandbox/handoff environment."""
from __future__ import annotations
import argparse, json, os, shutil, subprocess, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

TOOLS = [
    "python3", "jq", "rg", "grep", "sed", "awk", "find", "zip", "unzip", "sha256sum",
    "git", "make", "gcc", "clang", "node", "npm", "cargo", "rustc", "shellcheck", "yamllint",
    "markdownlint", "mdl", "typos", "taplo", "hdiutil", "diskutil", "fsck_apfs", "powershell", "pwsh",
]

PY_MODULES = ["json", "tomllib", "zipfile", "hashlib", "yaml"]

CAPABILITIES = {
    "python_static_checks": ["python3"],
    "json_queries": ["jq"],
    "source_search": ["rg", "grep"],
    "archive_validation": ["zip", "unzip", "sha256sum"],
    "c_compiler_available_for_small_helpers": ["gcc", "clang"],
    "node_available_for_future_docs_tools": ["node", "npm"],
    "rust_compile": ["cargo", "rustc"],
    "macos_apfs_fixture_generation": ["hdiutil", "diskutil"],
    "windows_mount_validation": ["powershell"],
}


def command_version(path: str) -> str | None:
    for args in ([path, "--version"], [path, "-version"], [path, "version"]):
        try:
            proc = subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, timeout=5)
        except Exception:
            continue
        if proc.stdout.strip():
            return proc.stdout.splitlines()[0].strip()
    return None


def module_available(name: str) -> bool:
    try:
        __import__(name)
        return True
    except Exception:
        return False


def build_inventory() -> dict:
    tools = []
    found = {}
    for tool in TOOLS:
        path = shutil.which(tool)
        found[tool] = bool(path)
        tools.append({
            "tool": tool,
            "available": bool(path),
            "path": path,
            "version": command_version(path) if path else None,
        })
    modules = [{"module": name, "available": module_available(name)} for name in PY_MODULES]
    caps = []
    for name, reqs in CAPABILITIES.items():
        missing = [req for req in reqs if not found.get(req)]
        caps.append({"capability": name, "available": not missing, "required_tools": reqs, "missing_tools": missing})
    return {
        "schema_version": (ROOT / "VERSION").read_text(encoding="utf-8").strip() if (ROOT / "VERSION").exists() else "unknown",
        "environment": {"platform": sys.platform, "cwd": str(ROOT)},
        "tools": tools,
        "python_modules": modules,
        "capabilities": caps,
        "summary": {
            "available_tools": sum(1 for item in tools if item["available"]),
            "missing_tools": sum(1 for item in tools if not item["available"]),
            "available_capabilities": sum(1 for item in caps if item["available"]),
            "missing_capabilities": sum(1 for item in caps if not item["available"]),
        },
    }


def write_markdown(inv: dict, path: Path) -> None:
    lines = ["# Current Environment Inventory", "", "Generated by `tools/current_environment_inventory.py`.", "", f"- Schema version: `{inv['schema_version']}`", f"- Platform: `{inv['environment']['platform']}`", "", "## Capabilities", "", "| Capability | Available | Missing tools |", "|---|---:|---|"]
    for cap in inv["capabilities"]:
        missing = ", ".join(cap["missing_tools"]) or "—"
        lines.append(f"| `{cap['capability']}` | `{str(cap['available']).lower()}` | {missing} |")
    lines += ["", "## Tools", "", "| Tool | Available | Path/version |", "|---|---:|---|"]
    for tool in inv["tools"]:
        detail = tool["path"] or "missing"
        if tool.get("version"):
            detail += f"<br>{tool['version']}"
        lines.append(f"| `{tool['tool']}` | `{str(tool['available']).lower()}` | {detail} |")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--json-out", type=Path, default=ROOT / "CURRENT_ENVIRONMENT.json")
    p.add_argument("--md-out", type=Path, default=ROOT / "CURRENT_ENVIRONMENT.md")
    args = p.parse_args()
    inv = build_inventory()
    args.json_out.write_text(json.dumps(inv, indent=2) + "\n", encoding="utf-8")
    write_markdown(inv, args.md_out)
    print(f"current-environment-inventory: wrote {args.json_out} and {args.md_out}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
