#!/usr/bin/env python3
"""Cargoless dependency policy audit.

This cannot know crate licences without network access or cargo metadata, but it
can inventory declared dependencies, identify workspace dependencies, and flag
high-risk dependency categories that need local cargo-deny/cargo-vet follow-up.
"""
from __future__ import annotations
import json
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / "DEPENDENCY_POLICY_AUDIT.json"
OUT_MD = ROOT / "DEPENDENCY_POLICY_AUDIT.md"
HIGH_RISK_NAMES = {"windows", "winapi", "ring", "openssl", "aes", "pbkdf2", "sha2", "fuser", "fuse3", "libc"}

def load_toml(path: Path) -> dict:
    return tomllib.loads(path.read_text(encoding="utf-8"))

def dependency_names(table) -> list[str]:
    if not isinstance(table, dict):
        return []
    return sorted(table.keys())

def main() -> int:
    root_manifest = load_toml(ROOT / "Cargo.toml")
    workspace_deps = dependency_names(root_manifest.get("workspace", {}).get("dependencies", {}))
    members = root_manifest.get("workspace", {}).get("members", [])
    crates = []
    all_declared: dict[str, set[str]] = {}
    for member in members:
        path = ROOT / member / "Cargo.toml"
        if not path.exists():
            continue
        manifest = load_toml(path)
        deps = dependency_names(manifest.get("dependencies", {}))
        dev_deps = dependency_names(manifest.get("dev-dependencies", {}))
        crates.append({"member": member, "dependencies": deps, "dev_dependencies": dev_deps})
        for dep in deps + dev_deps:
            all_declared.setdefault(dep, set()).add(member)
    high_risk = sorted(name for name in all_declared if name.lower() in HIGH_RISK_NAMES)
    report = {
        "schema_version": "0.25.0",
        "workspace_dependency_count": len(workspace_deps),
        "workspace_dependencies": workspace_deps,
        "member_count": len(crates),
        "members": crates,
        "declared_dependency_count": len(all_declared),
        "high_risk_dependency_names_requiring_local_review": high_risk,
        "status": "needs_local_cargo_deny_audit_vet" if high_risk else "inventory_only",
        "note": "No network/cargo metadata used; local cargo-deny/cargo-audit/cargo-vet still required.",
    }
    OUT_JSON.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    lines = ["# Dependency Policy Audit", "", "Generated by `tools/dependency_license_policy_check.py`.", "", f"Workspace dependency declarations: **{len(workspace_deps)}**", f"Declared dependency names across members: **{len(all_declared)}**", "", "## High-risk dependency names requiring local review", ""]
    if high_risk:
        lines += [f"- `{name}`" for name in high_risk]
    else:
        lines.append("No high-risk dependency names were found by the cargoless scanner.")
    lines += ["", "## Workspace dependencies", ""] + [f"- `{name}`" for name in workspace_deps]
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("dependency-policy-audit: passed")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
