#!/usr/bin/env python3
"""Audit the Astro 7 docs package scaffold without npm install."""
from __future__ import annotations
import json, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def fail(msg: str) -> None:
    print(f"docs-package-audit: ERROR: {msg}", file=sys.stderr)
    raise SystemExit(1)

def main() -> int:
    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    pkg_path = ROOT / "docs-site/package.json"
    pkg = json.loads(pkg_path.read_text(encoding="utf-8"))
    scripts = pkg.get("scripts", {})
    deps = pkg.get("devDependencies", {})
    astro = deps.get("astro")
    checks = []
    def check(name: str, ok: bool, detail: str) -> None:
        checks.append({"name": name, "ok": ok, "detail": detail})
        if not ok:
            fail(f"{name}: {detail}")
    check("private package", pkg.get("private") is True, "docs-site package must remain private")
    check("astro 7 pinned", astro == "7.0.2", f"expected astro 7.0.2, found {astro!r}")
    check("node engine", pkg.get("engines", {}).get("node", "").startswith(">=22"), "Node engine should be >=22")
    for script in ("dev", "build", "preview", "check"):
        check(f"script {script}", script in scripts and bool(str(scripts[script]).strip()), "script must exist")
    required_files = [
        "docs-site/astro.config.mjs",
        "docs-site/tsconfig.json",
        "docs-site/src/layouts/Base.astro",
        "docs-site/src/pages/index.astro",
        "docs-site/src/pages/quality.astro",
        "docs-site/src/pages/conductor.astro",
        "docs-site/src/pages/handoff.astro",
    ]
    for rel in required_files:
        path = ROOT / rel
        check(rel, path.exists() and path.read_text(encoding="utf-8").strip() != "", "required docs-site file missing or empty")
    envelope = {"schema_version": version, "status": "passed", "astro_version": astro, "checks": checks}
    (ROOT / "DOCS_PACKAGE_AUDIT.json").write_text(json.dumps(envelope, indent=2) + "\n", encoding="utf-8")
    lines = ["# Docs Package Audit", "", "Generated by `tools/docs_package_audit.py`.", "", f"- Astro package: `{astro}`", "- Status: `passed`", "", "| Check | OK | Detail |", "|---|---:|---|"]
    for c in checks:
        lines.append(f"| {c['name']} | {str(c['ok']).lower()} | {c['detail']} |")
    (ROOT / "DOCS_PACKAGE_AUDIT.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"docs-package-audit: passed ({len(checks)} checks)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
