#!/usr/bin/env python3
"""Generate a cargoless advanced-feature readiness snapshot."""
from __future__ import annotations
import argparse, json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def current_version(root: Path) -> str:
    version_file = root / 'VERSION'
    return version_file.read_text(encoding='utf-8').strip() if version_file.exists() else '0.0.0-dev'
FEATURES = [
    {
        "feature": "unicode-case-policy",
        "capability_id": "M-034",
        "status": "policy_scaffold",
        "cli": "apfs path-policy --json --name <component>",
        "production_ready": False,
        "missing": ["macOS APFS normalization fixture", "case-insensitive collision handling"],
    },
    {
        "feature": "xattrs-resource-forks",
        "capability_id": "M-035",
        "status": "readiness_scaffold",
        "cli": "apfs feature-readiness --json --feature xattrs",
        "production_ready": False,
        "missing": ["APFS extended-field parser", "resource fork payload extents", "hash oracle fixtures"],
    },
    {
        "feature": "sparse-clones",
        "capability_id": "M-036",
        "status": "readiness_scaffold",
        "cli": "apfs feature-readiness --json --feature sparse-clone",
        "production_ready": False,
        "missing": ["extent hole detection", "shared physical extent accounting", "streaming extraction policy"],
    },
    {
        "feature": "compression",
        "capability_id": "M-037",
        "status": "readiness_scaffold",
        "cli": "apfs feature-readiness --json --feature compression",
        "production_ready": False,
        "missing": ["decmpfs metadata parser", "zlib/lzvn/lzfse dependency review", "decompression bomb guards"],
    },
    {
        "feature": "snapshots-volume-roles",
        "capability_id": "M-038",
        "status": "readiness_scaffold",
        "cli": "apfs feature-readiness --json --feature snapshots",
        "production_ready": False,
        "missing": ["volume role validation", "snapshot metadata discovery", "read-only snapshot view selection"],
    },
]

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--root', type=Path, default=ROOT)
    parser.add_argument('--json-out', type=Path, default=None)
    parser.add_argument('--md-out', type=Path, default=None)
    args = parser.parse_args()
    root = args.root.resolve()
    json_out = args.json_out or root/'FEATURE_READINESS.json'
    md_out = args.md_out or root/'FEATURE_READINESS.md'
    envelope = {
        "schema_version": current_version(root),
        "status": "readiness_snapshot",
        "production_ready_count": sum(1 for f in FEATURES if f["production_ready"]),
        "feature_count": len(FEATURES),
        "features": FEATURES,
        "safety": {
            "read_only": True,
            "writes_to_apfs_media": False,
            "claims_production_support": False,
        },
    }
    json_out.write_text(json.dumps(envelope, indent=2) + '\n', encoding='utf-8')
    lines = [
        '# APFS-RS Advanced Feature Readiness', '',
        'Generated by `tools/feature_readiness_snapshot.py`.', '',
        f"- Feature readiness entries: **{len(FEATURES)}**",
        f"- Production-ready advanced features: **{envelope['production_ready_count']}**",
        '- Safety: read-only/report-only; no APFS media writes.', '',
        '| Feature | Capability | Status | CLI | Missing production work |',
        '|---|---|---|---|---|',
    ]
    for f in FEATURES:
        missing = '<br>'.join(f['missing'])
        lines.append(f"| {f['feature']} | {f['capability_id']} | {f['status']} | `{f['cli']}` | {missing} |")
    md_out.write_text('\n'.join(lines)+'\n', encoding='utf-8')
    print(f'feature-readiness-snapshot: wrote {json_out.relative_to(root)} and {md_out.relative_to(root)}')
    return 0
if __name__ == '__main__':
    raise SystemExit(main())
