#!/usr/bin/env python3
"""Generate cargoless golden-output expectations for synthetic fixtures.

These are lightweight expectations for later CLI tests. They do not execute the
Rust CLI; they encode the expected high-level status from fixture bytes and
manifests so that the first local cargo run has deterministic targets.
"""
from __future__ import annotations
import json
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GOLDEN_DIR = ROOT / "fixtures/golden"
OUT_JSON = ROOT / "GOLDEN_OUTPUTS.json"
OUT_MD = ROOT / "GOLDEN_OUTPUTS.md"

def classify_fixture(fixture_path: Path) -> dict:
    data = fixture_path.read_bytes() if fixture_path.exists() else b""
    rel = fixture_path.relative_to(ROOT).as_posix()
    status = "unknown"
    reason = "no rule matched"
    if len(data) < 184:
        status, reason = "refused", "shorter than nx_superblock_min_size"
    elif data[32:36] == b"NXSB":
        block_size = int.from_bytes(data[36:40], "little")
        if block_size < 512 or block_size & (block_size - 1) != 0:
            status, reason = "refused", "invalid block size"
        else:
            status, reason = "apfs_container_detected", "NXSB magic at block zero"
    elif len(data) >= 1024 and data[512:520] == b"EFI PART":
        status, reason = "gpt_probe", "GPT signature present; APFS partition probe expected"
    else:
        status, reason = "not_apfs", "no NXSB or GPT signature"
    return {
        "fixture": rel,
        "sha256": hashlib.sha256(data).hexdigest() if data else None,
        "expected_status": status,
        "reason": reason,
    }

def main() -> int:
    GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
    fixture_files = sorted(
        [p for p in (ROOT / "fixtures").iterdir() if p.is_file() and p.suffix in {".bin", ".img"}]
        + [p for p in (ROOT / "fixtures/negative").glob("*.bin")]
    )
    results = [classify_fixture(path) for path in fixture_files]
    for item in results:
        name = Path(item["fixture"]).name + ".expected.json"
        (GOLDEN_DIR / name).write_text(json.dumps(item, indent=2) + "\n", encoding="utf-8")
    report = {
        "schema_version": "0.25.0",
        "golden_count": len(results),
        "golden_dir": "fixtures/golden",
        "items": results,
        "note": "Cargoless high-level fixture expectations for future CLI tests.",
    }
    OUT_JSON.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    lines = ["# Golden Output Expectations", "", "Generated by `tools/golden_output_generator.py`.", "", "| Fixture | Expected status | Reason |", "|---|---|---|"]
    for item in results:
        lines.append(f"| `{item['fixture']}` | `{item['expected_status']}` | {item['reason']} |")
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"golden-output-generator: wrote {len(results)} golden expectations")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
