#!/usr/bin/env python3
"""Audit repository files before packaging a handoff archive."""
from __future__ import annotations
import argparse, hashlib, json, os
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
SKIP_DIRS = {".git", "target"}


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def iter_files():
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        yield path


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--json-out", type=Path, default=ROOT / "HANDOFF_ARCHIVE_AUDIT.json")
    p.add_argument("--md-out", type=Path, default=ROOT / "HANDOFF_ARCHIVE_AUDIT.md")
    args = p.parse_args()
    rows = []
    large = []
    for path in sorted(iter_files()):
        rel = path.relative_to(ROOT).as_posix()
        size = path.stat().st_size
        if size > 5 * 1024 * 1024:
            large.append(rel)
        rows.append({"path": rel, "size": size, "sha256": sha256(path)})
    payload = {"schema_version": (ROOT / "VERSION").read_text(encoding="utf-8").strip(), "file_count": len(rows), "large_files_over_5mb": large, "files": rows}
    args.json_out.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    lines = ["# Handoff Archive Audit", "", "Generated by `tools/handoff_archive_audit.py`.", "", f"- File count: **{len(rows)}**", f"- Large files over 5 MiB: **{len(large)}**", "", "| Path | Size | SHA-256 |", "|---|---:|---|"]
    for row in rows[:250]:
        lines.append(f"| `{row['path']}` | {row['size']} | `{row['sha256']}` |")
    if len(rows) > 250:
        lines.append(f"| … | {len(rows) - 250} additional files omitted from markdown; see JSON | … |")
    args.md_out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"handoff-archive-audit: wrote {args.json_out} and {args.md_out} ({len(rows)} files)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
