#!/usr/bin/env python3
"""Generate a loop/backlog dashboard from REMAINING_ELEMENTS.yaml and Conductor tracks."""
from __future__ import annotations
import argparse, json, sys
from pathlib import Path
try:
    import yaml  # type: ignore
except Exception:
    yaml = None
ROOT = Path(__file__).resolve().parents[1]

def load_yaml(path: Path):
    if yaml is None:
        print('loop-dashboard: PyYAML is required', file=sys.stderr)
        raise SystemExit(1)
    return yaml.safe_load(path.read_text(encoding='utf-8'))

def main() -> int:
    global ROOT
    parser=argparse.ArgumentParser()
    parser.add_argument('--out', type=Path, default=ROOT/'LOOP_DASHBOARD.md')
    parser.add_argument('--root', type=Path, default=ROOT)
    args=parser.parse_args()
    ROOT=args.root.resolve()
    ledger=load_yaml(ROOT/'REMAINING_ELEMENTS.yaml')
    summary=ledger['summary']
    implemented=ledger.get('implemented', [])
    mvp=ledger.get('remaining_windows_readonly_mvp', [])
    post=ledger.get('remaining_beyond_mvp', [])
    tracks=sorted(p.name for p in (ROOT/'conductor/tracks').iterdir() if p.is_dir())
    lines=['# APFS-RS Loop Dashboard','', 'Generated by `tools/loop_dashboard.py`.', '', '## Counts', '', f"- Implemented/scaffolded elements: **{summary['implemented_or_scaffolded']}**", f"- Remaining overall: **{summary['remaining_overall']}**", f"- Remaining Windows read-only MVP: **{summary['remaining_windows_readonly_mvp']}**", f"- Conductor tracks: **{len(tracks)}**", '', '## Next batched loop recommendation', '', '1. Run the Rust-enabled compile/test loop and repair compiler issues.', '2. Generate the first macOS APFS fixture and run the feedback loop.', '3. Promote feedback mismatches into Codev/Conductor tracks.', '4. Implement parser corrections in batches, preserving read-only safety gates.', '', '## Remaining Windows MVP elements', '', '| ID | Element | Dependency |', '|---|---|---|']
    for item in mvp:
        lines.append(f"| {item['id']} | {item['title']} | {item.get('dependency','')} |")
    lines += ['', '## Recent implemented/scaffolded elements', '', '| ID | Title | Category | Status |', '|---|---|---|---|']
    for item in implemented[-10:]:
        lines.append(f"| {item['id']} | {item['title']} | {item.get('category','')} | {item.get('status','')} |")
    lines += ['', '## Conductor tracks', '']
    for track in tracks:
        lines.append(f'- `{track}`')
    args.out.write_text('\n'.join(lines)+'\n', encoding='utf-8')
    print(f"loop-dashboard: wrote {args.out.relative_to(ROOT)}; remaining overall={summary['remaining_overall']}, mvp={summary['remaining_windows_readonly_mvp']}")
    return 0
if __name__=='__main__':
    raise SystemExit(main())
