#!/usr/bin/env python3
"""Promote APFS-RS real-fixture feedback into Codev and Conductor task stubs.

This tool reads the JSON report produced by ``tools/real_fixture_feedback.py`` and
creates an output bundle containing suggested Codev specs/plans/reviews and
Conductor tracks. It intentionally writes only to the requested output directory;
it does not modify the source tree, open APFS media, mount disks, decrypt data,
repair, format, or write filesystem structures.
"""
from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any


@dataclass
class PromotedTask:
    task_id: str
    track_id: str
    severity: str
    field: str
    message: str
    suggested_source_track: str
    codev_spec: str
    codev_plan: str
    codev_review: str
    conductor_track: str


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        value = json.load(handle)
    if not isinstance(value, dict):
        raise SystemExit(f"{path} must contain a JSON object")
    return value


def slugify(value: str, fallback: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    slug = re.sub(r"-+", "-", slug)
    return slug[:72] or fallback


def issue_list(report: dict[str, Any]) -> list[dict[str, Any]]:
    issues = report.get("issues")
    if not isinstance(issues, list):
        return []
    out: list[dict[str, Any]] = []
    for index, issue in enumerate(issues, start=1):
        if isinstance(issue, dict):
            normalized = {
                "severity": str(issue.get("severity") or "error"),
                "field": str(issue.get("field") or issue.get("path") or f"issue-{index:04}"),
                "message": str(issue.get("message") or issue.get("title") or "No message supplied"),
                "suggested_track": str(issue.get("suggested_track") or "0012-real-fixture-feedback-loop"),
                "title": str(issue.get("title") or issue.get("field") or issue.get("message") or "real fixture mismatch"),
                "raw": issue,
            }
            out.append(normalized)
        elif isinstance(issue, str):
            out.append({
                "severity": "error",
                "field": f"issue-{index:04}",
                "message": issue,
                "suggested_track": "0012-real-fixture-feedback-loop",
                "title": issue,
                "raw": issue,
            })
    return out


def promote(report: dict[str, Any], out_dir: Path, prefix: str) -> list[PromotedTask]:
    issues = [issue for issue in issue_list(report) if issue.get("severity") in {"blocker", "error", "warning"}]
    out_dir.mkdir(parents=True, exist_ok=True)
    tasks: list[PromotedTask] = []

    for index, issue in enumerate(issues, start=1):
        field = str(issue.get("field") or f"issue-{index}")
        severity = str(issue.get("severity") or "error")
        message = str(issue.get("message") or "No message supplied")
        suggested = str(issue.get("suggested_track") or "0012-real-fixture-feedback-loop")
        slug = slugify(field, f"issue-{index}")
        task_id = f"RF-{index:03d}"
        track_id = f"{prefix}-{index:03d}-{slug}"

        codev_spec_path = Path("codev/specs") / f"{track_id}.md"
        codev_plan_path = Path("codev/plans") / f"{track_id}.md"
        codev_review_path = Path("codev/reviews") / f"{track_id}-review.md"
        conductor_track_path = Path("conductor/tracks") / track_id

        write_codev_spec(out_dir / codev_spec_path, task_id, track_id, severity, field, message, suggested, report)
        write_codev_plan(out_dir / codev_plan_path, task_id, track_id, field, message)
        write_codev_review(out_dir / codev_review_path, task_id, track_id)
        write_conductor_track(out_dir / conductor_track_path, task_id, track_id, severity, field, message, suggested, codev_spec_path, codev_plan_path, codev_review_path, report)

        tasks.append(PromotedTask(
            task_id=task_id,
            track_id=track_id,
            severity=severity,
            field=field,
            message=message,
            suggested_source_track=suggested,
            codev_spec=str(codev_spec_path),
            codev_plan=str(codev_plan_path),
            codev_review=str(codev_review_path),
            conductor_track=str(conductor_track_path),
        ))

    write_index(out_dir, report, tasks)
    return tasks


def write_codev_spec(path: Path, task_id: str, track_id: str, severity: str, field: str, message: str, suggested: str, report: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fixture_id = report.get("fixture_id") or "unknown"
    text = f"""# Spec: {task_id} {field}

Generated by: `tools/promote_feedback_to_tracks.py`  
Generated track: `{track_id}`  
Source fixture: `{fixture_id}`  
Severity: `{severity}`  
Suggested source track: `{suggested}`

## Problem

`{field}` did not match the current real-fixture expectation.

```text
{message}
```

## Goal

Investigate and correct the read-only APFS inspection/parser behaviour or update the redacted fixture manifest if the manifest expectation is wrong.

## Safety requirements

- Read JSON artifacts and APFS images read-only only.
- Do not mount, decrypt, repair, format, or write APFS media.
- Do not use personal data or secret-bearing fixtures.
- Preserve Codev and Conductor traceability.

## Acceptance

- Root cause recorded.
- Parser/manifest change made, if required.
- Synthetic or real-fixture check added/updated.
- Feedback report rerun and this issue no longer appears, or is explicitly documented as an accepted limitation.
"""
    path.write_text(text, encoding="utf-8")


def write_codev_plan(path: Path, task_id: str, track_id: str, field: str, message: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = f"""# Plan: {task_id} {field}

Generated track: `{track_id}`

## Steps

1. Read the feedback issue and associated real-fixture manifest.
2. Reproduce with `apfs inspect --json` and `cargo xtask real-fixture-feedback`.
3. Identify whether the mismatch is a parser bug, manifest bug, missing feature, or expected unsupported state.
4. Implement the smallest read-only change or update the manifest with evidence.
5. Add or update tests/fixtures.
6. Rerun feedback and record results.
7. Update Codev review and Conductor track metadata.

## Original feedback

```text
{message}
```

## Non-goals

- Write support.
- Mount support.
- Repair or format.
- Encryption bypass.
"""
    path.write_text(text, encoding="utf-8")


def write_codev_review(path: Path, task_id: str, track_id: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = f"""# Review: {task_id} {track_id}

Status: generated_pending_investigation

## What changed

Pending.

## Evidence

Pending.

## Safety result

Pending. Must remain read-only.

## Follow-up

Pending.
"""
    path.write_text(text, encoding="utf-8")


def write_conductor_track(path: Path, task_id: str, track_id: str, severity: str, field: str, message: str, suggested: str, codev_spec: Path, codev_plan: Path, codev_review: Path, report: dict[str, Any]) -> None:
    path.mkdir(parents=True, exist_ok=True)
    metadata = {
        "track_id": track_id,
        "title": f"{task_id}: real-fixture feedback for {field}",
        "status": "generated_pending_investigation",
        "created_from": "real-fixture-feedback",
        "source_fixture": report.get("fixture_id"),
        "severity": severity,
        "field": field,
        "suggested_source_track": suggested,
        "codev_spec": str(codev_spec),
        "codev_plan": str(codev_plan),
        "codev_review": str(codev_review),
    }
    (path / "metadata.json").write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (path / "spec.md").write_text(f"""# Track {track_id} Spec

## Source

Generated from real-fixture feedback issue `{task_id}`.

## Field

`{field}`

## Feedback

```text
{message}
```

## Requirement

Resolve this mismatch through read-only parser work, fixture manifest correction, or explicit unsupported-state documentation.

## Safety

This track must not introduce write, mount, repair, format, decryption, password recovery, or raw physical-device access.
""", encoding="utf-8")
    (path / "plan.md").write_text(f"""# Track {track_id} Plan

1. Reproduce the mismatch.
2. Locate the parser or manifest source of truth.
3. Make the smallest read-only correction.
4. Add/update tests.
5. Rerun real-fixture feedback.
6. Update this track status and Codev review.
""", encoding="utf-8")


def write_index(out_dir: Path, report: dict[str, Any], tasks: list[PromotedTask]) -> None:
    index_json = {
        "schema_version": "0.13.0",
        "status": "no_tasks" if not tasks else "tasks_generated",
        "source_feedback_status": report.get("status"),
        "fixture_id": report.get("fixture_id"),
        "task_count": len(tasks),
        "tasks": [asdict(task) for task in tasks],
        "safety_note": "Generated tasks are planning artifacts only. No APFS media is opened, mounted, decrypted, repaired, formatted, or written.",
    }
    (out_dir / "task-index.json").write_text(json.dumps(index_json, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    lines = [
        "# APFS-RS Promoted Real-Fixture Feedback Tasks",
        "",
        f"Status: `{index_json['status']}`",
        f"Fixture: `{index_json.get('fixture_id') or 'unknown'}`",
        f"Task count: {len(tasks)}",
        "",
        "## Safety note",
        "",
        index_json["safety_note"],
        "",
        "## Tasks",
        "",
    ]
    if not tasks:
        lines.append("No blocker/error/warning feedback issues were found.")
    else:
        for task in tasks:
            lines.extend([
                f"### {task.task_id}: `{task.field}`",
                "",
                f"- Track: `{task.track_id}`",
                f"- Severity: `{task.severity}`",
                f"- Suggested source track: `{task.suggested_source_track}`",
                f"- Codev spec: `{task.codev_spec}`",
                f"- Conductor track: `{task.conductor_track}`",
                "",
                task.message,
                "",
            ])
    (out_dir / "task-index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("feedback_json", type=Path)
    parser.add_argument("out_dir", type=Path)
    parser.add_argument("--prefix", default="generated-real-fixture", help="track-id prefix for generated tasks")
    args = parser.parse_args()

    report = load_json(args.feedback_json)
    tasks = promote(report, args.out_dir, args.prefix)
    print(f"generated {len(tasks)} task(s) in {args.out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
