#!/usr/bin/env python3
"""Generate a repository manifest for handoff packages."""
from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKIP_PARTS = {
    ".astro",
    ".git",
    "__pycache__",
    "apfs-rs-impl-v0.29",
    "dist",
    "node_modules",
    "target",
}


def classify(path: Path) -> str:
    parts = path.parts
    if parts[0] == "crates":
        return "rust_crates"
    if parts[0] == "codev":
        return "codev_context"
    if parts[0] == "conductor":
        return "conductor_context"
    if parts[0] == "tools":
        return "python_tools"
    if parts[0] == "fixtures":
        return "fixtures"
    if parts[0] == ".github":
        return "github_automation"
    if parts[0] in {"packaging", ".devcontainer", ".cargo", ".config"}:
        return "developer_tooling"
    return "root_docs_or_config"


def build_manifest() -> dict:
    files = []
    for path in sorted(ROOT.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(ROOT)
        if any(part in SKIP_PARTS for part in rel.parts):
            continue
        files.append({"path": rel.as_posix(), "bytes": path.stat().st_size, "category": classify(rel)})
    counts = Counter(item["category"] for item in files)
    return {"schema_version": "0.21.0", "file_count": len(files), "categories": dict(sorted(counts.items())), "files": files}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    manifest = build_manifest()
    if args.write:
        (ROOT / "REPO_MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
        lines = ["# Repository Manifest", "", f"Schema version: {manifest['schema_version']}", "", f"Files: {manifest['file_count']}", "", "## Categories", ""]
        for category, count in manifest["categories"].items():
            lines.append(f"- `{category}`: {count}")
        lines.extend(["", "## Notes", "", "This manifest is generated by `tools/repo_manifest.py --write` for local handoff review."])
        (ROOT / "REPO_MANIFEST.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
        print("repo-manifest: wrote REPO_MANIFEST.json and REPO_MANIFEST.md")
    else:
        print(json.dumps(manifest, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
