#!/usr/bin/env python3
"""Generate simple cargoless source/repository metrics."""
from __future__ import annotations
import argparse, json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def count_lines(paths):
    total = 0
    files = 0
    for path in paths:
        if path.is_file():
            files += 1
            total += len(path.read_text(encoding='utf-8', errors='ignore').splitlines())
    return files, total

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--root', type=Path, default=ROOT)
    args = parser.parse_args()
    root = args.root.resolve()
    rust_files = list((root / 'crates').rglob('*.rs')) + list((root / 'xtask').rglob('*.rs'))
    python_files = list((root / 'tools').glob('*.py'))
    md_files = [p for p in root.rglob('*.md') if 'target' not in p.parts]
    json_files = [p for p in root.rglob('*.json') if 'target' not in p.parts]
    conductor_tracks = [p for p in (root / 'conductor/tracks').iterdir() if p.is_dir()]
    rust_file_count, rust_lines = count_lines(rust_files)
    py_file_count, py_lines = count_lines(python_files)
    md_file_count, md_lines = count_lines(md_files)
    unsafe_hits = []
    for path in rust_files:
        text = path.read_text(encoding='utf-8', errors='ignore')
        for idx, line in enumerate(text.splitlines(), 1):
            if 'unsafe' in line and 'forbid(unsafe_code)' not in line and 'unsafe-looking' not in line:
                unsafe_hits.append({'path': path.relative_to(root).as_posix(), 'line': idx, 'text': line.strip()})
    payload = {
        'schema_version': '0.18.0',
        'rust_files': rust_file_count,
        'rust_lines': rust_lines,
        'python_tool_files': py_file_count,
        'python_tool_lines': py_lines,
        'markdown_files': md_file_count,
        'markdown_lines': md_lines,
        'json_files': len(json_files),
        'conductor_tracks': len(conductor_tracks),
        'unsafe_hits': unsafe_hits,
    }
    (root / 'SOURCE_METRICS.json').write_text(json.dumps(payload, indent=2) + '\n', encoding='utf-8')
    lines = ['# APFS-RS Source Metrics', '', 'Generated by `tools/source_metrics.py`.', '', '| Metric | Value |', '|---|---:|']
    for key in ['rust_files','rust_lines','python_tool_files','python_tool_lines','markdown_files','markdown_lines','json_files','conductor_tracks']:
        lines.append(f"| `{key}` | {payload[key]} |")
    lines += ['', '## Unsafe token findings', '']
    if unsafe_hits:
        for hit in unsafe_hits:
            lines.append(f"- `{hit['path']}:{hit['line']}` {hit['text']}")
    else:
        lines.append('- None outside approved lint/checker contexts.')
    (root / 'SOURCE_METRICS.md').write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f"source-metrics: wrote SOURCE_METRICS.json and SOURCE_METRICS.md (rust_lines={rust_lines}, tracks={len(conductor_tracks)})")
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
