#!/usr/bin/env python3
"""Inventory unit/integration/e2e/property/fuzz/mutation/profiling test scaffolds."""
from __future__ import annotations
import json, re, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def fail(msg: str) -> None:
    print(f"test-inventory-report: ERROR: {msg}", file=sys.stderr)
    raise SystemExit(1)

def exists(pattern: str) -> list[str]:
    return sorted(str(p.relative_to(ROOT)) for p in ROOT.glob(pattern) if p.exists())

def main() -> int:
    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    categories = {
        "unit_tests": exists("crates/*/src/lib.rs"),
        "integration_tests": exists("crates/*/tests/*.rs") + exists("tests/integration/*"),
        "e2e_tests": exists("crates/*/tests/e2e*.rs") + exists("tests/e2e/*"),
        "property_tests_rust": exists("crates/*/tests/*property*.rs") + exists("tests/property/*"),
        "hypothesis_tests_python": exists("python_tests/test*.py"),
        "fuzz_targets": exists("fuzz/fuzz_targets/*.rs"),
        "mutation_config": exists("mutants.toml") + exists(".config/cargo-mutants.toml"),
        "benchmarks": exists("crates/*/benches/*.rs") + exists("benches/*") + exists("profiling/*"),
        "coverage_config": exists(".config/cargo-llvm-cov.toml") + exists(".github/workflows/coverage.yml"),
    }
    minimums = {
        "integration_tests": 1,
        "e2e_tests": 1,
        "property_tests_rust": 1,
        "hypothesis_tests_python": 1,
        "fuzz_targets": 2,
        "mutation_config": 1,
        "benchmarks": 1,
        "coverage_config": 1,
    }
    checks = []
    for name, files in categories.items():
        min_count = minimums.get(name, 1)
        ok = len(files) >= min_count
        checks.append({"category": name, "count": len(files), "minimum": min_count, "ok": ok, "files": files})
        if not ok:
            fail(f"{name} has {len(files)}, expected at least {min_count}")
    envelope = {"schema_version": version, "status": "passed", "checks": checks}
    (ROOT / "TEST_INVENTORY_REPORT.json").write_text(json.dumps(envelope, indent=2) + "\n", encoding="utf-8")
    lines = ["# Test Inventory Report", "", "Generated by `tools/test_inventory_report.py`.", "", "| Category | Count | Minimum | OK |", "|---|---:|---:|---:|"]
    for c in checks:
        lines.append(f"| `{c['category']}` | {c['count']} | {c['minimum']} | `{str(c['ok']).lower()}` |")
    lines.append("\n## Files\n")
    for c in checks:
        lines.append(f"### {c['category']}")
        for f in c["files"][:50]:
            lines.append(f"- `{f}`")
        if len(c["files"]) > 50:
            lines.append(f"- ... {len(c['files']) - 50} more")
        lines.append("")
    (ROOT / "TEST_INVENTORY_REPORT.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"test-inventory-report: passed ({len(checks)} categories)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
