#!/usr/bin/env python3
"""Generate a phase-aware test/control matrix for APFS-RS."""
from __future__ import annotations
import argparse, json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

MATRIX = [
    {"phase": "current_environment", "command": "python3 tools/precompile_static_check.py", "purpose": "cargoless source/context/fixture sanity", "required_now": True},
    {"phase": "current_environment", "command": "python3 tools/synthetic_fixture_oracle.py", "purpose": "synthetic fixture shape/oracle checks", "required_now": True},
    {"phase": "current_environment", "command": "python3 tools/current_environment_inventory.py", "purpose": "available tool inventory", "required_now": True},
    {"phase": "current_environment", "command": "python3 tools/current_env_remaining.py", "purpose": "classify remaining work by environment", "required_now": True},
    {"phase": "current_environment", "command": "python3 tools/cargo_dependency_graph.py", "purpose": "workspace path dependency graph", "required_now": True},
    {"phase": "local_rust", "command": "cargo fmt --all -- --check", "purpose": "Rust formatting", "required_now": False},
    {"phase": "local_rust", "command": "cargo test --workspace", "purpose": "compile and unit tests", "required_now": False},
    {"phase": "local_rust", "command": "cargo clippy --workspace --all-targets --all-features -- -D warnings", "purpose": "Rust linting", "required_now": False},
    {"phase": "macos_fixture", "command": "./tools/macos/create_real_apfs_fixture.sh", "purpose": "real APFS sparse image fixture", "required_now": False},
    {"phase": "windows_winfsp", "command": "cargo run -p apfs-cli -- winfsp-callback-matrix --json", "purpose": "read-only mount contract before live adapter", "required_now": False},
]


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--json-out", type=Path, default=ROOT / "TEST_CONTROL_MATRIX.json")
    p.add_argument("--md-out", type=Path, default=ROOT / "TEST_CONTROL_MATRIX.md")
    args = p.parse_args()
    payload = {"schema_version": (ROOT / "VERSION").read_text(encoding="utf-8").strip(), "checks": MATRIX}
    args.json_out.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    lines = ["# Test and Control Matrix", "", "Generated by `tools/test_matrix_generator.py`.", "", "| Phase | Command | Purpose | Required now |", "|---|---|---|---:|"]
    for item in MATRIX:
        lines.append(f"| `{item['phase']}` | `{item['command']}` | {item['purpose']} | `{str(item['required_now']).lower()}` |")
    args.md_out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"test-matrix-generator: wrote {args.json_out} and {args.md_out}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
