#!/usr/bin/env python3
"""Generate a Markdown traceability matrix across requirements, Codev, and Conductor."""
from __future__ import annotations
import argparse, json, re, sys
from pathlib import Path
try:
    import yaml  # type: ignore
except Exception:
    yaml = None
ROOT = Path(__file__).resolve().parents[1]

def load_yaml(path: Path):
    if yaml is None:
        print("traceability-matrix: PyYAML is required", file=sys.stderr)
        raise SystemExit(1)
    return yaml.safe_load(path.read_text(encoding='utf-8'))

def first_file(patterns):
    for pattern in patterns:
        matches = sorted(ROOT.glob(pattern))
        if matches:
            return matches[0]
    return None

def find_track_for_cap(cap_id: str) -> Path | None:
    cap_lower = cap_id.lower()
    for meta_path in sorted((ROOT/'conductor/tracks').glob('*/metadata.json')):
        track = meta_path.parent.name.lower()
        text = (meta_path.parent/'spec.md').read_text(encoding='utf-8', errors='ignore').lower() + '\n' + (meta_path.parent/'plan.md').read_text(encoding='utf-8', errors='ignore').lower()
        if cap_lower in track or cap_lower in text:
            return meta_path.parent
    return None

def main() -> int:
    global ROOT
    parser=argparse.ArgumentParser()
    parser.add_argument('--out', type=Path, default=ROOT/'TRACEABILITY.md')
    parser.add_argument('--root', type=Path, default=ROOT)
    args=parser.parse_args()
    ROOT=args.root.resolve()
    caps=load_yaml(ROOT/'codev/resources/capabilities.yaml')['capabilities']
    rows=[]
    for cap_id, cap in caps.items():
        spec=first_file([f'codev/specs/*{cap_id.lower()}*.md', f'codev/specs/*{cap_id[2:].lower()}*.md'])
        plan=first_file([f'codev/plans/*{cap_id.lower()}*.md', f'codev/plans/*{cap_id[2:].lower()}*.md'])
        review=first_file([f'codev/reviews/*{cap_id.lower()}*.md', f'codev/reviews/*{cap_id[2:].lower()}*.md'])
        track=find_track_for_cap(cap_id)
        rows.append((cap_id, cap.get('name',''), cap.get('moscow',''), cap.get('milestone',''), cap.get('status', cap.get('status_note','')), spec, plan, review, track))
    lines=['# APFS-RS Traceability Matrix','', 'Generated by `tools/traceability_matrix.py`.', '', '| Capability | MoSCoW | Milestone | Status | Codev spec | Codev plan | Codev review | Conductor track |', '|---|---|---|---|---|---|---|---|']
    for cap_id,name,moscow,milestone,status,spec,plan,review,track in rows:
        def rel(p): return f'`{p.relative_to(ROOT)}`' if p else 'missing'
        lines.append(f'| {cap_id}: {name} | {moscow} | {milestone} | {status} | {rel(spec)} | {rel(plan)} | {rel(review)} | {rel(track)} |')
    args.out.write_text('\n'.join(lines)+'\n', encoding='utf-8')
    print(f'traceability-matrix: wrote {args.out.relative_to(ROOT)} with {len(rows)} capabilities')
    return 0
if __name__=='__main__':
    raise SystemExit(main())
