#!/usr/bin/env python3
"""Cargoless version consistency check for the current source package."""
from __future__ import annotations
import argparse, json, sys
from pathlib import Path
try:
    import yaml  # type: ignore
except Exception:
    yaml = None
ROOT = Path(__file__).resolve().parents[1]
CURRENT_FILES = [
    'VERSION',
    'REMAINING_ELEMENTS.yaml',
    'codev/resources/capabilities.yaml',
    'codev/resources/safety-gates.yaml',
    'FEATURE_READINESS.json',
    'CLI_CONTRACT.json',
    'API_SURFACE.json',
]
TEXT_FILES_SHOULD_MENTION = [
    'README.md',
    'REQUIREMENTS.md',
    'DESIGN.md',
    'REMAINING_ELEMENTS.md',
    'conductor/tracks.md',
    'conductor/history.md',
]

def fail(msg: str) -> None:
    print(f'version-consistency-check: ERROR: {msg}', file=sys.stderr)
    raise SystemExit(1)

def load_yaml(path: Path):
    if yaml is None:
        fail('PyYAML is required')
    return yaml.safe_load(path.read_text(encoding='utf-8'))

def main() -> int:
    global ROOT
    parser=argparse.ArgumentParser()
    parser.add_argument('--root', type=Path, default=ROOT)
    parser.add_argument('--json-out', type=Path, default=None)
    parser.add_argument('--md-out', type=Path, default=None)
    args=parser.parse_args()
    ROOT=args.root.resolve()
    version=(ROOT/'VERSION').read_text(encoding='utf-8').strip()
    checks=[]
    for rel in CURRENT_FILES:
        p=ROOT/rel
        if not p.exists(): fail(f'missing {rel}')
        text=p.read_text(encoding='utf-8', errors='ignore')
        if rel.endswith('.yaml'):
            data=load_yaml(p)
            observed=str(data.get('schema_version',''))
        elif rel.endswith('.json'):
            data=json.loads(text)
            observed=str(data.get('schema_version',''))
        else:
            observed=text.strip()
        ok=(observed==version)
        checks.append({'file':rel,'observed_version':observed,'expected_version':version,'ok':ok})
        if not ok:
            fail(f'{rel} has version {observed!r}, expected {version!r}')
    for rel in TEXT_FILES_SHOULD_MENTION:
        p=ROOT/rel
        if not p.exists(): fail(f'missing {rel}')
        ok=version in p.read_text(encoding='utf-8', errors='ignore')
        checks.append({'file':rel,'mentions_version':version,'ok':ok})
        if not ok:
            fail(f'{rel} does not mention current version {version}')
    envelope={'schema_version':version,'status':'passed','checks':checks}
    json_out=args.json_out or ROOT/'VERSION_CONSISTENCY.json'
    md_out=args.md_out or ROOT/'VERSION_CONSISTENCY.md'
    json_out.write_text(json.dumps(envelope, indent=2)+'\n', encoding='utf-8')
    lines=['# APFS-RS Version Consistency', '', 'Generated by `tools/version_consistency_check.py`.', '', f'- Current version: **{version}**', '', '| File | Check | OK |', '|---|---|---|']
    for check in checks:
        detail=check.get('observed_version') or check.get('mentions_version') or ''
        lines.append(f"| `{check['file']}` | `{detail}` | `{str(check['ok']).lower()}` |")
    md_out.write_text('\n'.join(lines)+'\n', encoding='utf-8')
    print(f'version-consistency-check: passed ({len(checks)} checks)')
    return 0
if __name__=='__main__':
    raise SystemExit(main())
