
name: mutation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'

permissions:
  contents: read

jobs:
  cargo-mutants:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: taiki-e/install-action@9bcaee1dcae34154180f412e2fa69355a7cda9f6
        with:
          tool: cargo-mutants,nextest
      - run: cargo mutants --workspace --timeout 300 --output target/mutants
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        if: always()
        with:
          name: cargo-mutants-report
          path: target/mutants
